### ISSUE TITLE
Name not descriptive

### ISSUE THREAD

**Issue by 3cbb** [cis3296s22/SimpleTunes#20]
When downloading the app from the internet, the name of the package is "app-debug.apk". This tells you nothing about the app and appears suspicious, as well as being difficult to find in systems that are in active use.

**Comment by free-mana** [comment]
This is the default name that Android Studio gives for the APK. Theoretically, if this were to be actually released, users wouldn't be dealing with the APK anyway-- they'd just download it from the Google Play store.

Still, this is a valid criticism, so future releases will have "SimpleTunes" in the name of the APK.
