### ISSUE TITLE
Buillds runs, can't get avd manager to appear

### ISSUE THREAD

**Issue by tui92851** [cis3296s22/SimpleTunes#59]
![yhOz0mw](https://user-images.githubusercontent.com/89498580/161780306-b0ae2b9b-3dd6-4385-bda3-bbdbb89ed33e.png)
I included an image of what happens, the build runs succesfully but my AVD manager seems to never actually run the application.  I have changed the settings to allow unknown apps.

**Comment by free-mana** [comment]
Closing issue due to no response.
