### ISSUE TITLE
After loading songs from a folder, the repeat button doesn't work

### ISSUE THREAD

**Issue by SkylerShaw** [cis3296s22/SimpleTunes#66]
Also, as a suggestion, please show some visual feedback for the buttons as it is hard to tell if they have been pressed already or not.

**Comment by free-mana** [comment]
Repeat functionality has not been implemented yet, it's part of the current sprint. Button animation will be investigated.

**Comment by free-mana** [comment]
Issues #69 and #70 have been completed, so this issue is now complete.
